### ISSUE TITLE
Adding an ip address manually does not make it unusable from automatic selection

### ISSUE THREAD

**Issue by telmich** [telmich/cinv#1]
[16:56] brief:.sexy% sexy net-ipv4 host-add -m de:ad:ca:fe:ba:be -f router-net.example.com -i 77.109.138.1 77.109.138.0                                                                                                                    

[17:04] brief:.sexy% sexy net-ipv4 host-ipv4-address-get -f kvmtest.example.org 77.109.138.0 
77.109.138.1

**Comment by toupeira** [comment]
@telmich I think we just ran into the same issue, we had an IP already used for an IPMI device and added it to cinv, assuming it would get skipped when allocating new IP addresses for VMs, but it assigned it anyway and after a lot of head-scratching we finally realized why we couldn't connect to the VM ;-)

**Comment by telmich** [comment]
@toupeira can you try PR #2 ?

**Comment by darko-poljak** [comment]
@toupeira Any feedback?

**Comment by toupeira** [comment]
@darko-poljak sorry almost forgot about this! Tested it now, there's one small problem in that it also picks the gateway IP (`.1`), but if I add that to cinv as well it works fine afterwards (and reuses lower IPs from deleted hosts which is great), but the gateway problem will probably trip up other users. Maybe a warning in the README/CHANGELOG is sufficient though?

**Comment by telmich** [comment]
The problem here is that gateway=1 is just a convention, many networks use .253, .254, etc. And if == .1 in a /22 does not have any meaning.

Even if I would like to avoid this problem, I think there is no generic solution for this problem

**Comment by darko-poljak** [comment]
@toupeira I think this gateway problem was here before this change.
Isn't it that gateway can have arbitrary IP address so cinv cannot guess its address?
The same for other special assigned addresses.
And probably the right thing is to add special/static addresses first.
Sure we can skip first few addresses but this is guessing common case.
So perhaps you are right about warning in docs.
@telmich What do you think?

**Comment by darko-poljak** [comment]
@telmich At the same moment... :)

**Comment by toupeira** [comment]
@telmich / @darko-poljak yes I agree with both of you, and I definitely didn't mean you should hard-code `.1` :)

**Comment by darko-poljak** [comment]
@telmich Then this issue is fixed :)

**Comment by darko-poljak** [comment]
Fixed with https://github.com/telmich/cinv/pull/2
